# -*- coding: utf-8 -*-
"""lab3_pyhton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dB9Y8wovmkE4UGq4sRRrDlx5exoTIzy
"""

#third

import pi from math
def area_of_circle(r):
    r= int(input("ENter a radius"))
    area_of_circle = pi*r**2
    return(area_of_circle)
print(area_of_circle(5))

print("*****")
print("*   *")
print("*   *")
print("*****")

#fifth

#definitionOfVariables
daysOfWorkPerMonth = 20
monthsInYear = 12
vacation = 26
yearsOfWOrk = 40
#result
print((daysOfWorkPerMonth * monthsInYear - vacation)*yearsOfWOrk)

#sixth

print('TVP1','TVN','Polsat','BBC')
print('TVP1','TVN','Polsat','BBC', sep='\n')
print('TVP1','TVN','Polsat','BBC', sep='\t')
print('TVP1','TVN','Polsat','BBC', sep=';')
print('TVP1','TVN','Polsat','BBC', sep='-')
print('I like computers ','TVP1','TVN','Polsat','BBC', sep=' but better is ')
#variables definition
ProgramName = 'BBC'
Item = 'News'
Time = '18:00'
print('I like watching',Item,'at',Time,'on',ProgramName,'.')
print('I like watching ',Item,' at ',Time,' on ',ProgramName,'.', sep='')
print('\u03A3') # the sum character as a Unicode character code
print('this is a backslash: \\') #backslash has a particular meaning...

r =float(input("Enter a number"))
valuepi=3.14
peri =2*valuepi*r
print("perimeter of the circle is",peri)
area = valuepi*r**r
print("area of the circle is",area)
l=float(input("Enter a number"))
b=float(input("Enter a number"))
rectangle = l*b
print("the area of rectangle is,", rectangle)
d1=float(input("Enter a number"))
d2=float(input("Enter a number"))
h=float(input("Enter a number"))
area_of_trap = ((d1+d2)/2)*h
print("The area of trapezium,",area_of_trap)

print("(\\(\\")
print(" (-.-)")
print("O_(\")(\")")

